from PyQt5 import QtCore, QtGui, QtWidgets
from Custom_Widgets.Widgets import QCustomSlideMenu, QCustomStackedWidget
import QSS_Resources_rc


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1031, 626)
        MainWindow.setStyleSheet("*{\n"
"    border: none;\n"
"    background-color:transparent;\n"
"    background:transparent;\n"
"    padding:0;\n"
"    margin:0;\n"
"    color: #fff;\n"
"}\n"
"#centralwidget, #mainBodyContent, QLineEdit{\n"
"    background-color:#1b1b27;\n"
"}\n"
"#header, #mainBody, #footer{\n"
"    background-color: #27263c;\n"
"}\n"
"#pushButton{\n"
"    border:1px solid #cc5bce;\n"
"    border-radius: 17px;\n"
"    text-align:center;\n"
"}\n"
"#addUserBtn{\n"
"    background-color: #cc5bce;\n"
"    border-radius: 13px;\n"
"}\n"
"#leftMenu, QPushButton{\n"
"    text-align:left;\n"
"    padding: 5px 10px;\n"
"    border-top-left-radius: 10px;\n"
"    border-bottom-left-radius: 10px;\n"
"    border-top-right-radius: 0px;\n"
"    border-bottom-right-radius: 0px;\n"
"    background-color:transparent;\n"
"}\n"
"#homeBtn{\n"
"    border-left:3px solid #cc5bce;\n"
"    font-weight:bold;\n"
"    background-color:#1b1b27;\n"
"}\n"
"QLineEdit{\n"
"    color:#fff;\n"
"    padding: 5px 10px;\n"
"    border-radius: 5px\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.header = QtWidgets.QWidget(self.centralwidget)
        self.header.setObjectName("header")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.header)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_2 = QtWidgets.QFrame(self.header)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.menuBtn = QtWidgets.QPushButton(self.frame_2)
        self.menuBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.menuBtn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/Icons/align-justify.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menuBtn.setIcon(icon)
        self.menuBtn.setIconSize(QtCore.QSize(22, 22))
        self.menuBtn.setObjectName("menuBtn")
        self.horizontalLayout_4.addWidget(self.menuBtn, 0, QtCore.Qt.AlignLeft)
        self.label = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.horizontalLayout.addWidget(self.frame_2, 0, QtCore.Qt.AlignLeft)
        self.frame = QtWidgets.QFrame(self.header)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.frame)
        self.pushButton_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_4.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/Icons/search.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon1)
        self.pushButton_4.setIconSize(QtCore.QSize(22, 22))
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_3.addWidget(self.pushButton_4)
        self.pushButton_3 = QtWidgets.QPushButton(self.frame)
        self.pushButton_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_3.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/Icons/bell.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon2)
        self.pushButton_3.setIconSize(QtCore.QSize(22, 22))
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_3.addWidget(self.pushButton_3)
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_2.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/Icons/activity.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon3)
        self.pushButton_2.setIconSize(QtCore.QSize(22, 22))
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_3.addWidget(self.pushButton_2)
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setMinimumSize(QtCore.QSize(35, 35))
        self.pushButton.setMaximumSize(QtCore.QSize(35, 35))
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/Icons/user.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon4)
        self.pushButton.setIconSize(QtCore.QSize(25, 25))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_3.addWidget(self.pushButton)
        self.horizontalLayout.addWidget(self.frame, 0, QtCore.Qt.AlignRight)
        self.verticalLayout.addWidget(self.header, 0, QtCore.Qt.AlignTop)
        self.mainBody = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mainBody.sizePolicy().hasHeightForWidth())
        self.mainBody.setSizePolicy(sizePolicy)
        self.mainBody.setMinimumSize(QtCore.QSize(944, 499))
        self.mainBody.setObjectName("mainBody")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.mainBody)
        self.horizontalLayout_2.setContentsMargins(0, -1, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.leftMenu = QCustomSlideMenu(self.mainBody)
        self.leftMenu.setMinimumSize(QtCore.QSize(200, 0))
        self.leftMenu.setObjectName("leftMenu")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.leftMenu)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 20)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widget = QtWidgets.QWidget(self.leftMenu)
        self.widget.setMinimumSize(QtCore.QSize(200, 470))
        self.widget.setObjectName("widget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_4.setContentsMargins(10, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_3 = QtWidgets.QFrame(self.widget)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(10)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.homeBtn = QtWidgets.QPushButton(self.frame_3)
        self.homeBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.homeBtn.setStyleSheet("background-color:#1b1b27;")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/Icons/home.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.homeBtn.setIcon(icon5)
        self.homeBtn.setObjectName("homeBtn")
        self.verticalLayout_5.addWidget(self.homeBtn)
        self.reportsBtn = QtWidgets.QPushButton(self.frame_3)
        self.reportsBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/Icons/printer.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.reportsBtn.setIcon(icon6)
        self.reportsBtn.setObjectName("reportsBtn")
        self.verticalLayout_5.addWidget(self.reportsBtn)
        self.accountBtn = QtWidgets.QPushButton(self.frame_3)
        self.accountBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.accountBtn.setIcon(icon4)
        self.accountBtn.setObjectName("accountBtn")
        self.verticalLayout_5.addWidget(self.accountBtn)
        self.verticalLayout_4.addWidget(self.frame_3)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.frame_4 = QtWidgets.QFrame(self.widget)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(10)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.settingBtn = QtWidgets.QPushButton(self.frame_4)
        self.settingBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/Icons/settings.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.settingBtn.setIcon(icon7)
        self.settingBtn.setObjectName("settingBtn")
        self.verticalLayout_6.addWidget(self.settingBtn)
        self.helpBtn = QtWidgets.QPushButton(self.frame_4)
        self.helpBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/Icons/help-circle.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.helpBtn.setIcon(icon8)
        self.helpBtn.setObjectName("helpBtn")
        self.verticalLayout_6.addWidget(self.helpBtn)
        self.aboutBtn = QtWidgets.QPushButton(self.frame_4)
        self.aboutBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icons/Icons/info.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.aboutBtn.setIcon(icon9)
        self.aboutBtn.setObjectName("aboutBtn")
        self.verticalLayout_6.addWidget(self.aboutBtn)
        self.verticalLayout_4.addWidget(self.frame_4)
        self.verticalLayout_3.addWidget(self.widget)
        self.horizontalLayout_2.addWidget(self.leftMenu)
        self.mainBodyContent = QtWidgets.QWidget(self.mainBody)
        self.mainBodyContent.setObjectName("mainBodyContent")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.mainBodyContent)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.mainPages = QCustomStackedWidget(self.mainBodyContent)
        self.mainPages.setObjectName("mainPages")
        self.homePage = QtWidgets.QWidget()
        self.homePage.setObjectName("homePage")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.homePage)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.widget_3 = QtWidgets.QWidget(self.homePage)
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.frame_6 = QtWidgets.QFrame(self.widget_3)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_8 = QtWidgets.QLabel(self.frame_6)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_6.addWidget(self.label_8, 0, QtCore.Qt.AlignLeft)
        self.showUserFromBtn = QtWidgets.QPushButton(self.frame_6)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.showUserFromBtn.setFont(font)
        self.showUserFromBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/icons/Icons/file-plus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.showUserFromBtn.setIcon(icon10)
        self.showUserFromBtn.setIconSize(QtCore.QSize(22, 22))
        self.showUserFromBtn.setObjectName("showUserFromBtn")
        self.horizontalLayout_6.addWidget(self.showUserFromBtn, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_11.addWidget(self.frame_6)
        self.tableWidget = QtWidgets.QTableWidget(self.widget_3)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self.verticalLayout_11.addWidget(self.tableWidget)
        self.verticalLayout_10.addWidget(self.widget_3)
        self.mainPages.addWidget(self.homePage)
        self.reportsPage = QtWidgets.QWidget()
        self.reportsPage.setObjectName("reportsPage")
        self.label_7 = QtWidgets.QLabel(self.reportsPage)
        self.label_7.setGeometry(QtCore.QRect(120, 140, 181, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.mainPages.addWidget(self.reportsPage)
        self.accountsPage = QtWidgets.QWidget()
        self.accountsPage.setObjectName("accountsPage")
        self.label_6 = QtWidgets.QLabel(self.accountsPage)
        self.label_6.setGeometry(QtCore.QRect(160, 170, 181, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.mainPages.addWidget(self.accountsPage)
        self.settingsPage = QtWidgets.QWidget()
        self.settingsPage.setObjectName("settingsPage")
        self.label_5 = QtWidgets.QLabel(self.settingsPage)
        self.label_5.setGeometry(QtCore.QRect(170, 160, 181, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.mainPages.addWidget(self.settingsPage)
        self.helpPage = QtWidgets.QWidget()
        self.helpPage.setObjectName("helpPage")
        self.label_4 = QtWidgets.QLabel(self.helpPage)
        self.label_4.setGeometry(QtCore.QRect(170, 110, 181, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.mainPages.addWidget(self.helpPage)
        self.aboutPage = QtWidgets.QWidget()
        self.aboutPage.setObjectName("aboutPage")
        self.label_3 = QtWidgets.QLabel(self.aboutPage)
        self.label_3.setGeometry(QtCore.QRect(190, 140, 181, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.mainPages.addWidget(self.aboutPage)
        self.verticalLayout_2.addWidget(self.mainPages)
        self.horizontalLayout_2.addWidget(self.mainBodyContent)
        self.rightMenu = QCustomSlideMenu(self.mainBody)
        self.rightMenu.setMinimumSize(QtCore.QSize(200, 0))
        self.rightMenu.setObjectName("rightMenu")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.rightMenu)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.widget_2 = QtWidgets.QWidget(self.rightMenu)
        self.widget_2.setMinimumSize(QtCore.QSize(196, 249))
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_2 = QtWidgets.QLabel(self.widget_2)
        self.label_2.setMinimumSize(QtCore.QSize(70, 70))
        self.label_2.setMaximumSize(QtCore.QSize(70, 70))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/icons/Icons/edit.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_8.addWidget(self.label_2, 0, QtCore.Qt.AlignHCenter)
        self.frame_5 = QtWidgets.QFrame(self.widget_2)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.userName = QtWidgets.QLineEdit(self.frame_5)
        self.userName.setObjectName("userName")
        self.verticalLayout_9.addWidget(self.userName)
        self.email = QtWidgets.QLineEdit(self.frame_5)
        self.email.setObjectName("email")
        self.verticalLayout_9.addWidget(self.email)
        self.phoneNo = QtWidgets.QLineEdit(self.frame_5)
        self.phoneNo.setObjectName("phoneNo")
        self.verticalLayout_9.addWidget(self.phoneNo)
        self.verticalLayout_8.addWidget(self.frame_5)
        self.addUserBtn = QtWidgets.QPushButton(self.widget_2)
        self.addUserBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.addUserBtn.setIcon(icon10)
        self.addUserBtn.setIconSize(QtCore.QSize(22, 22))
        self.addUserBtn.setObjectName("addUserBtn")
        self.verticalLayout_8.addWidget(self.addUserBtn, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_7.addWidget(self.widget_2, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.horizontalLayout_2.addWidget(self.rightMenu)
        self.verticalLayout.addWidget(self.mainBody)
        self.footer = QtWidgets.QWidget(self.centralwidget)
        self.footer.setObjectName("footer")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.footer)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_9 = QtWidgets.QLabel(self.footer)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_5.addWidget(self.label_9, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout.addWidget(self.footer)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "My Apps"))
        self.homeBtn.setText(_translate("MainWindow", "Home"))
        self.reportsBtn.setText(_translate("MainWindow", "Reports"))
        self.accountBtn.setText(_translate("MainWindow", "My Account"))
        self.settingBtn.setText(_translate("MainWindow", "Settings"))
        self.helpBtn.setText(_translate("MainWindow", "Help"))
        self.aboutBtn.setText(_translate("MainWindow", "About"))
        self.label_8.setText(_translate("MainWindow", "Home"))
        self.showUserFromBtn.setText(_translate("MainWindow", "Add User Detail"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Username"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Email"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Phone Number"))
        self.label_7.setText(_translate("MainWindow", "Reports"))
        self.label_6.setText(_translate("MainWindow", "Account"))
        self.label_5.setText(_translate("MainWindow", "Setting"))
        self.label_4.setText(_translate("MainWindow", "Help"))
        self.label_3.setText(_translate("MainWindow", "About"))
        self.userName.setPlaceholderText(_translate("MainWindow", "Username"))
        self.email.setPlaceholderText(_translate("MainWindow", "Email"))
        self.phoneNo.setPlaceholderText(_translate("MainWindow", "Phone Number"))
        self.addUserBtn.setText(_translate("MainWindow", "Add User"))
        self.label_9.setText(_translate("MainWindow", "Hassan | Copyright 2023"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
